#!/usr/bin/env bash
# configure.sh — interactively ask the handful of values and write lab.conf.
# Run once on a fresh server (the paste-bootstrap calls it). No more hand-editing.
# Values go into lab.conf (host-local, gitignored) — the RUNBOOK stays generic.
set -euo pipefail
LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$LAB_DIR/lab.conf"

# Read from the real terminal even when this script was launched at the tail of a
# pasted block (so the pasted text isn't consumed as our answers).
TTY="${CONFIGURE_TTY:-/dev/tty}"

# If lab.conf already exists, offer to reuse its values as defaults.
[ -f "$CONF" ] && { echo "lab.conf already exists — its values will be the defaults (Enter keeps them)."; # shellcheck disable=SC1090
	source "$CONF"; }

# --- sensible auto-detected defaults ---------------------------------------
det_ip="$(ip -4 route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1)"
[ -z "$det_ip" ] && det_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
det_tz="$(timedatectl show -p Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo UTC)"
det_gname="$(git config --global user.name 2>/dev/null || true)"
det_gemail="$(git config --global user.email 2>/dev/null || true)"

# ask VAR "prompt" "default"   (empty default => required, loops until answered)
ask() {
	local __var="$1" __prompt="$2" __def="${3:-}" __in=""
	if [ -n "$__def" ]; then
		read -rp "  $__prompt [$__def]: " __in <"$TTY" || true
		__in="${__in:-$__def}"
	else
		until [ -n "$__in" ]; do read -rp "  $__prompt: " __in <"$TTY" || true; done
	fi
	printf -v "$__var" '%s' "$__in"
}

echo
echo "── Configure this lab (writes lab.conf) ───────────────────────────────"
ask DOMAIN        "Domain (must already be on Cloudflare)"        "${DOMAIN:-}"
ask GITHUB_OWNER  "GitHub account/org for app repos"              "${GITHUB_OWNER:-}"
ask LAB_USER      "OS login user that owns ~/lab and ~/apps"      "${LAB_USER:-$USER}"
ask LAN_IP        "Server LAN/VPN IP (reach apps directly)"       "${LAN_IP:-$det_ip}"
ask LAB_NAME      "Lab name (secrets dir -> /etc/<name>)"         "${LAB_NAME:-$LAB_USER}"
ask TUNNEL        "Cloudflare tunnel name"                        "${TUNNEL:-${LAB_NAME}-tunnel}"
ask TIMEZONE      "Timezone (tz database name)"                   "${TIMEZONE:-$det_tz}"
ask GIT_USER_NAME "Git commit name"                               "${GIT_USER_NAME:-${det_gname:-$LAB_USER}}"
ask GIT_USER_EMAIL "Git commit email"                             "${GIT_USER_EMAIL:-$det_gemail}"

cat > "$CONF" <<EOF
# lab.conf — generated by configure.sh. Host-local, gitignored. Edit freely.
DOMAIN="$DOMAIN"
LAN_IP="$LAN_IP"
LAB_USER="$LAB_USER"
LAB_NAME="$LAB_NAME"
TUNNEL="$TUNNEL"
GITHUB_OWNER="$GITHUB_OWNER"
TIMEZONE="$TIMEZONE"
GIT_USER_NAME="$GIT_USER_NAME"
GIT_USER_EMAIL="$GIT_USER_EMAIL"

# Port conventions (rarely changed — edit here if needed):
PORT_MIN=8080
PORT_MAX=8099
DASHBOARD_PORT=5005   # dashboard / :80 catch-all target
GATE_PORT=8082        # login gateway (forward-auth)
EOF

echo
echo "✅ Wrote $CONF:"
sed 's/^/     /' "$CONF"
echo
echo "Next:"
echo "  • Tell your agent:  \"Follow AGENTS.md / RUNBOOK.md to finish setting up this server.\""
echo "  • Or continue by hand: ./bootstrap.sh   (then the RUNBOOK happy path: tunnel login, etc.)"
