#!/usr/bin/env bash
# configure.sh — interactively ask the handful of values and write setup.conf.
# Run once on a fresh server (the paste-bootstrap calls it). No more hand-editing.
# Values go into setup.conf (host-local, gitignored) — the RUNBOOK stays generic.
set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$SETUP_DIR/setup.conf"

# Read from the real terminal even when this script was launched at the tail of a
# pasted block (so the pasted text isn't consumed as our answers).
TTY="${CONFIGURE_TTY:-/dev/tty}"

# If setup.conf already exists, offer to reuse its values as defaults.
[ -f "$CONF" ] && { echo "setup.conf already exists — its values will be the defaults (Enter keeps them)."; # shellcheck disable=SC1090
	source "$CONF"; }

# --- sensible auto-detected defaults ---------------------------------------
det_ip="$(ip -4 route get 1.1.1.1 2>/dev/null | grep -oP 'src \K[0-9.]+' | head -1)"
[ -z "$det_ip" ] && det_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
det_tz="$(timedatectl show -p Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo UTC)"
det_gname="$(git config --global user.name 2>/dev/null || true)"
det_gemail="$(git config --global user.email 2>/dev/null || true)"

# ask VAR "prompt" "default"   (empty default => required, loops until answered)
ask() {
	local __var="$1" __prompt="$2" __def="${3:-}" __in=""
	if [ -n "$__def" ]; then
		read -rp "  $__prompt [$__def]: " __in <"$TTY" || true
		__in="${__in:-$__def}"
	else
		until [ -n "$__in" ]; do read -rp "  $__prompt: " __in <"$TTY" || true; done
	fi
	printf -v "$__var" '%s' "$__in"
}

# ask_secret VAR "prompt"   (hidden input; blank allowed with a warning)
ask_secret() {
	local __var="$1" __prompt="$2" __in=""
	read -rsp "  $__prompt: " __in <"$TTY" || true; echo
	printf -v "$__var" '%s' "$__in"
}

echo
echo "── Configure this server (writes setup.conf) ───────────────────────────────"
ask DOMAIN        "Domain (must already be on Cloudflare)"        "${DOMAIN:-}"
ask GITHUB_OWNER  "GitHub account/org for app repos"              "${GITHUB_OWNER:-}"
ask SETUP_USER      "OS login user that owns ~/server-setup and ~/apps"      "${SETUP_USER:-$USER}"
ask LAN_IP        "Server LAN/VPN IP (reach apps directly)"       "${LAN_IP:-$det_ip}"
ask SETUP_NAME      "Setup name (secrets dir -> /etc/<name>)"         "${SETUP_NAME:-$SETUP_USER}"
ask TUNNEL        "Cloudflare tunnel name"                        "${TUNNEL:-${SETUP_NAME}-tunnel}"
ask TIMEZONE      "Timezone (tz database name)"                   "${TIMEZONE:-$det_tz}"
ask GIT_USER_NAME "Git commit name"                               "${GIT_USER_NAME:-${det_gname:-$SETUP_USER}}"
ask GIT_USER_EMAIL "Git commit email"                             "${GIT_USER_EMAIL:-$det_gemail}"
echo "  ── Shared login (one identity across the gate + every app) ──"
ask ADMIN_USER    "App login username"                           "${ADMIN_USER:-admin}"
ask ADMIN_EMAIL   "Admin email (for apps that need email)"       "${ADMIN_EMAIL:-$GIT_USER_EMAIL}"
SETUP_PASSWORD_PREV="${SETUP_PASSWORD:-}"
ask_secret SETUP_PASSWORD "Shared production password (hidden; Enter keeps existing)"
SETUP_PASSWORD="${SETUP_PASSWORD:-$SETUP_PASSWORD_PREV}"

cat > "$CONF" <<EOF
# setup.conf — generated by configure.sh. Host-local, gitignored, chmod 600. NEVER commit.
DOMAIN="$DOMAIN"
LAN_IP="$LAN_IP"
SETUP_USER="$SETUP_USER"
SETUP_NAME="$SETUP_NAME"
TUNNEL="$TUNNEL"
GITHUB_OWNER="$GITHUB_OWNER"
TIMEZONE="$TIMEZONE"
GIT_USER_NAME="$GIT_USER_NAME"
GIT_USER_EMAIL="$GIT_USER_EMAIL"

# Shared login (the gate splash page + every app's own login):
ADMIN_USER="$ADMIN_USER"
ADMIN_EMAIL="$ADMIN_EMAIL"
SETUP_PASSWORD="$SETUP_PASSWORD"

# Port conventions (rarely changed — edit here if needed):
PORT_MIN=8080
PORT_MAX=8099
DASHBOARD_PORT=5005   # dashboard / :80 catch-all target
GATE_PORT=8082        # login gateway (forward-auth)
EOF
chmod 600 "$CONF"   # contains SETUP_PASSWORD

[ -z "$SETUP_PASSWORD" ] && echo "  ⚠ SETUP_PASSWORD is empty — set it in setup.conf before deploying gated apps."
echo
echo "✅ Wrote $CONF (chmod 600). Password shown masked below:"
sed -E 's/^(SETUP_PASSWORD=).*/\1"********"/; s/^/     /' "$CONF"
echo
echo "Next — config is done; the host still needs the install steps (in order):"
echo "  • Easiest:  tell your agent  \"Follow AGENTS.md / RUNBOOK.md to set up this server.\""
echo "  • By hand:  install prereqs (Docker, Caddy, cloudflared, gh) → tunnel login/create →"
echo "              then ./bootstrap.sh   (it checks prereqs and wires the host)."
echo "    Start at RUNBOOK.md ★ Pre-flight. (bootstrap.sh won't run until Caddy etc. are installed.)"
